import { Assignment, Dealer, DealerPayment, DealerPaymentAllocation, Employee, EmployeeCommission, EmployeePayment, EmployeePaymentAllocation, SettlementTransaction, Statement } from '../types';
const isConfirmed = (t: SettlementTransaction) => t.status === 'confirmed';
const sum = (list: SettlementTransaction[], type: SettlementTransaction['type']) => list.filter((t) => t.type === type && isConfirmed(t)).reduce((a, t) => a + t.amount, 0);
const signedAdj = (tx: SettlementTransaction[], scope: 'shareable_net' | 'dealer_receivable_only') => tx.filter((t) => t.type === 'manual_adjustment' && t.adjustmentScope === scope && isConfirmed(t)).reduce((a, t) => a + (t.adjustmentDirection === 'decrease' ? -t.amount : t.amount), 0);
export function calculateStatementTotals(statement: Statement, transactions: SettlementTransaction[], dealer: Dealer, paidAmountOverride?: number) { const scoped = transactions.filter((t) => t.statementId === statement.id); const total_bank_payouts = sum(scoped, 'bank_payout'); const total_store_expenses = sum(scoped, 'store_expense'); const total_printing_costs = sum(scoped, 'printing_cost'); const total_shipping_costs = sum(scoped, 'shipping_cost'); const adj_shareable = signedAdj(scoped, 'shareable_net'); const adj_receivable = signedAdj(scoped, 'dealer_receivable_only'); const shareable_net_amount = total_bank_payouts - total_store_expenses + adj_shareable; const company_share_amount = shareable_net_amount * dealer.companySharePercentage; const dealer_receivable_amount = company_share_amount + total_printing_costs + total_shipping_costs + adj_receivable; const paid = paidAmountOverride ?? statement.paidAmount; return { dealer_receivable_amount, remaining_amount: dealer_receivable_amount - paid, paid_amount: paid, total_bank_payouts, total_store_expenses, total_printing_costs, total_shipping_costs, shareable_net_amount, company_share_amount }; }
export const getStatementPaidAmount = (statementId: string, allocations: DealerPaymentAllocation[]) => allocations.filter((a) => a.statementId === statementId).reduce((s, a) => s + a.allocatedAmount, 0);
export const getStatementRemainingAmount = (statement: Statement, transactions: SettlementTransaction[], dealer: Dealer, allocations: DealerPaymentAllocation[]) => calculateStatementTotals(statement, transactions, dealer, getStatementPaidAmount(statement.id, allocations)).remaining_amount;
export const getOpenStatementsForDealer = (dealerId: string, statements: Statement[], transactions: SettlementTransaction[], dealers: Dealer[], allocations: DealerPaymentAllocation[]) => { const d = dealers.find((x) => x.id === dealerId); if (!d) return []; return statements.filter((s) => s.dealerId === dealerId).map((s) => ({ statement: s, remaining: getStatementRemainingAmount(s, transactions, d, allocations) })).filter((x) => x.remaining > 0); };
export const getDealerOpenBalance = (dealerId: string, statements: Statement[], transactions: SettlementTransaction[], dealers: Dealer[], allocations: DealerPaymentAllocation[]) => getOpenStatementsForDealer(dealerId, statements, transactions, dealers, allocations).reduce((a, x) => a + x.remaining, 0);
export const getCurrentMonthReceivable = (dealerId: string, statements: Statement[], transactions: SettlementTransaction[], dealers: Dealer[], allocations: DealerPaymentAllocation[], currentMonth = '2026-04') => { const d = dealers.find((x) => x.id === dealerId); if (!d) return 0; return statements.filter((s) => s.dealerId === dealerId && s.month === currentMonth).reduce((a, s) => a + calculateStatementTotals(s, transactions, d).dealer_receivable_amount, 0); };
export const getDashboardTotals = (statements: Statement[], transactions: SettlementTransaction[], dealers: Dealer[], allocations: DealerPaymentAllocation[]) => ({ openBalance: dealers.reduce((a, d) => a + getDealerOpenBalance(d.id, statements, transactions, dealers, allocations), 0), currentMonthReceivable: dealers.reduce((a, d) => a + getCurrentMonthReceivable(d.id, statements, transactions, dealers, allocations), 0), pendingCount: transactions.filter((t) => t.status === 'pending_review').length });
export function allocateDealerPaymentFIFO({ amount, openStatements }: { dealerId: string; amount: number; openStatements: { statement: Statement; remaining: number }[] }) { const sorted = [...openStatements].sort((a, b) => (a.statement.month.localeCompare(b.statement.month) || (a.statement.createdAt || '').localeCompare(b.statement.createdAt || ''))); let left = amount; const allocations: { statementId: string; allocatedAmount: number }[] = []; for (const row of sorted) { if (left <= 0) break; const applied = Math.min(left, row.remaining); if (applied > 0) { allocations.push({ statementId: row.statement.id, allocatedAmount: applied }); left -= applied; } } return allocations; }
export function getDealerLedgerRows(dealerId: string, statements: Statement[], transactions: SettlementTransaction[], dealers: Dealer[], payments: DealerPayment[]) { const d = dealers.find((x) => x.id === dealerId); if (!d) return []; const rows: { date: string; kind: string; description: string; amount: number }[] = []; statements.filter((s) => s.dealerId === dealerId).forEach((s) => { const t = calculateStatementTotals(s, transactions, d); rows.push({ date: s.month, kind: 'Statement', description: `${s.month} settlement`, amount: t.dealer_receivable_amount }); }); payments.filter((p) => p.dealerId === dealerId).forEach((p) => rows.push({ date: p.paymentDate, kind: 'Payment Received', description: p.description || 'Dealer payment', amount: -p.amount })); return rows.sort((a, b) => a.date.localeCompare(b.date)); }

const getEmpAdj=(tx:SettlementTransaction[],statementId:string)=>tx.filter(t=>t.statementId===statementId&&t.type==='manual_adjustment'&&t.adjustmentScope==='employee_commission_base'&&t.status==='confirmed').reduce((a,t)=>a+(t.adjustmentDirection==='decrease'?-t.amount:t.amount),0);
export function calculateEmployeeCommissionForStatement(statement: Statement, transactions: SettlementTransaction[], dealer: Dealer, assignment: Assignment, employeeId: string): EmployeeCommission { const totals=calculateStatementTotals(statement,transactions,dealer); const adj=getEmpAdj(transactions,statement.id); const raw=totals.company_share_amount-totals.total_printing_costs-totals.total_shipping_costs+adj; const commissionBase=Math.max(raw,0); const commissionRate=assignment.commissionRatePct/100; const commissionAmount=Math.max(commissionBase*commissionRate,0); const [y,m]=statement.month.split('-').map(Number); return {id:`ec-${employeeId}-${statement.id}`,employeeId,dealerId:dealer.id,statementId:statement.id,periodMonth:m,periodYear:y,companyShareAmount:totals.company_share_amount,printingCosts:totals.total_printing_costs,shippingCosts:totals.total_shipping_costs,commissionBaseAdjustments:adj,commissionBase,commissionRate,commissionAmount,paidAmount:0,remainingAmount:commissionAmount,status:commissionAmount>0?'open':'closed',createdAt:new Date().toISOString()}; }
export function generateEmployeeCommissionsForStatement(statement: Statement, dealers: Dealer[], employees: Employee[], transactions: SettlementTransaction[], existing: EmployeeCommission[]) { const dealer=dealers.find(d=>d.id===statement.dealerId); if(!dealer) return existing; const out=[...existing]; for(const emp of employees){ const asg=emp.assignments.find(a=>a.storeId===dealer.storeId); if(!asg) continue; const calc=calculateEmployeeCommissionForStatement(statement,transactions,dealer,asg,emp.id); const i=out.findIndex(c=>c.employeeId===emp.id&&c.statementId===statement.id); if(i<0) out.push(calc); else if(!['paid','partially_paid'].includes(out[i].status)){ const paid=out[i].paidAmount; out[i]={...calc,paidAmount:paid,remainingAmount:Math.max(calc.commissionAmount-paid,0),status:paid>0?'partially_paid':calc.status}; }} return out; }
export const getEmployeeCommissionPaidAmount=(commissionId:string,allocs:EmployeePaymentAllocation[])=>allocs.filter(a=>a.commissionId===commissionId).reduce((s,a)=>s+a.allocatedAmount,0);
export const getEmployeeCommissionRemainingAmount=(c:EmployeeCommission,allocs:EmployeePaymentAllocation[])=>Math.max(c.commissionAmount-getEmployeeCommissionPaidAmount(c.id,allocs),0);
export const getOpenCommissionsForEmployee=(employeeId:string,commissions:EmployeeCommission[],allocs:EmployeePaymentAllocation[])=>commissions.filter(c=>c.employeeId===employeeId).map(c=>({commission:c,remaining:getEmployeeCommissionRemainingAmount(c,allocs)})).filter(x=>x.remaining>0);
export const getEmployeeOpenCommissionBalance=(employeeId:string,commissions:EmployeeCommission[],allocs:EmployeePaymentAllocation[])=>getOpenCommissionsForEmployee(employeeId,commissions,allocs).reduce((a,x)=>a+x.remaining,0);
export const getCurrentMonthEmployeeCommission=(employeeId:string,commissions:EmployeeCommission[],y=2026,m=4)=>commissions.filter(c=>c.employeeId===employeeId&&c.periodYear===y&&c.periodMonth===m).reduce((a,c)=>a+c.commissionAmount,0);
export const getEmployeeCommissionLedgerRows=(employeeId:string,commissions:EmployeeCommission[],payments:EmployeePayment[])=>{const rows:any[]=[]; commissions.filter(c=>c.employeeId===employeeId).forEach(c=>rows.push({date:`${c.periodYear}-${String(c.periodMonth).padStart(2,'0')}`,kind:'Commission',amount:c.commissionAmount,commission:c})); payments.filter(p=>p.employeeId===employeeId).forEach(p=>rows.push({date:p.paymentDate,kind:'Payment',amount:-p.amount,payment:p})); return rows.sort((a,b)=>a.date.localeCompare(b.date));};
